# ==========================================================
# ADD DEPENDENCY THAT ABAUBLE ONLY FOR A CONCRETE LIBRARY
# ==========================================================

add_library(${ADDITIONAL_DEPENDENCY_NAME} STATIC IMPORTED)
set_target_properties(${ADDITIONAL_DEPENDENCY_NAME} PROPERTIES
  IMPORTED_LOCATION
    ${ADDITIONAL_DEPENDENCY_STATIC_LIBRARY_FILE}
  INTERFACE_INCLUDE_DIRECTORIES
    ${ADDITIONAL_DEPENDENCY_INCLUDE_FOLDER}
)

file(COPY
  ${ADDITIONAL_DEPENDENCY_INCLUDE_FOLDER}
  DESTINATION "${ALL_EXTERNAL_INCLUDE_DIR}"
)

target_link_libraries(${LIBRARY_NAME}
  PRIVATE
    ${ADDITIONAL_DEPENDENCY_NAME}
)
